// AdminFLData.js
// This file transforms the existing FLData into the Admin Reviewer Schema,
// using tzLookup to assign correct timezones, countries, and explicit base coordinates.

const tzLookup = {
    "alyssakristins@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "beatricesolon@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "becca@peerlinkmedical.com": { timezone: "America/Chicago", country: "United States", baseLat: 41.8781, baseLng: -87.6298 },
    "kudiakubueze@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "chrisekundare@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "dilay.akcan@gmail.com": { timezone: "Europe/Istanbul", country: "Turkey", baseLat: 41.0082, baseLng: 28.9784 },
    "ebenezerarisa17@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "eo.uduigwome@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "elizagomeztoro4545@gmail.com": { timezone: "America/Bogota", country: "Colombia", baseLat: 4.7110, baseLng: -74.0721 },
    "theerikajee@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "grpayales@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "Ieva.puidoke@gmail.com": { timezone: "Europe/Vilnius", country: "Lithuania", baseLat: 54.6872, baseLng: 25.2797 },
    "ilerioluwalawal@outlook.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "iyanuopemipo@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "joshuaarisa14@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "joanoajayi@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "khwaishvasnani@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "linis2791@gmail.com": { timezone: "America/Bogota", country: "Colombia", baseLat: 4.7110, baseLng: -74.0721 },
    "lorensgee1@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "cornillezjoyce@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "lojamaja@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "oluseyekoluremi@su.edu.ph": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "damilolamogunsemowo@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "thomasoyinlola@yahoo.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "ravithaleva@gmail.com": { timezone: "Europe/Istanbul", country: "Turkey", baseLat: 41.0082, baseLng: 28.9784 },
    "sarahw445@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "shailamaramara@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "medicielo.prosvincent@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "will@peerlinkmedical.com": { timezone: "America/Chicago", country: "United States", baseLat: 41.8781, baseLng: -87.6298 },
    "iyannsaavedra@gmail.com": { timezone: "Asia/Manila", country: "Philippines", baseLat: 14.5995, baseLng: 120.9842 },
    "temilolaedun@outlook.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "nt.merari@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "pelumio.gabriel@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "to.ajayimd@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "addison@peerlinkmedical.com": { timezone: "America/Chicago", country: "United States", baseLat: 41.8781, baseLng: -87.6298 },
    "goodluckmodii@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "fiyinmlebi@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "elizabethmadeyanju@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "opemipomade@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "lebarimdamgbor@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "uchemejike@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "oluwaseyimadare@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "mariammakubo@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "jamiumolorunnisola@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "alameenmkalejaiye@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "solomonmbailey@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 },
    "oluwafemimdurojaiye@gmail.com": { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 }
  };
  
  // For any email not found in tzLookup, we use a default:
  const defaultTz = { timezone: "Africa/Lagos", country: "Nigeria", baseLat: 6.5244, baseLng: 3.3792 };
  
  const caseLengthOptions = ["≤200", "200-500", "500-1000", "1000+", "Any"];
  
  // Helper to get timezone info for an email:
  const getTzInfo = (email) => tzLookup[email] || defaultTz;
  
  // Updated AdminFLData array with explicit latitude and longitude values:
  const AdminFLData = [
    {
      id: 1,
      mra_id: 1,
      name: "Alyssa Teves",
      email: "alyssakristins@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_1.jpg",
      location: {
        country: "Philippines",
        latitude: 14.5995,
        longitude: 121.2842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Muckleshoot"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 5, Hartford: -10, "Peer Review": -20, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 3,
      caseLengthPreference: "200-500",
      currentWorkload: 1,
      availability: "Available",
      onTimePercentage: 92,
      accuracyScore: 64.84,
      overallQualityScore: 75.85,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 13,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 2,
      mra_id: 2,
      name: "Beatrice Solon",
      email: "beatricesolon@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_2.jpg",
      location: {
        country: "Philippines",
        latitude: 15.5995,
        longitude: 120.9842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "Telco", "LTC"],
      caseType: "Both",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: -10, Lincoln: 5, Hartford: 5, "Peer Review": 10, Telco: 0, NYL: 0, Standard: 0, LTC: 20 },
      dailyCaseLimit: 4,
      caseLengthPreference: "500-1000",
      currentWorkload: 2,
      availability: "Available",
      onTimePercentage: 75,
      accuracyScore: 70.37,
      overallQualityScore: 75.27,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 14,
      revisionAvailability: "Available",
      lastSnapshot: "2025-01-02T12:34:56Z"
    },
    {
      id: 3,
      mra_id: 3,
      name: "Becca Kennedy",
      email: "becca@peerlinkmedical.com",
      headshotUrl: "https://example.com/headshots/mra_3.jpg",
      location: {
        country: "United States",
        latitude: 33.4071,
        longitude: -86.7111,
        timezone: "America/Chicago"
      },
      clients: ["PFR", "Lincoln"],
      caseType: "Psych",
      preferredSpecialties: [],
      clientModifiers: { PFR: 1, Lincoln: -5, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      nonPreferredSpecialties: ["neuropsychology", "neuropsych"],
      dailyCaseLimit: 5,
      caseLengthPreference: "1000+",
      currentWorkload: 3,
      availability: "Available",
      onTimePercentage: 88,
      accuracyScore: 50.0,
      overallQualityScore: 66.4,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 15,
      revisionAvailability: "Available",
      lastSnapshot: "2024-06-11T12:34:56Z"
    },
    {
      id: 4,
      mra_id: 4,
      name: "Chukwudi Akubueze",
      email: "kudiakubueze@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_4.jpg",
      location: {
        country: "Nigeria",
        latitude: 6.5244,
        longitude: 3.8792,
        timezone: "Africa/Lagos"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "Telco", "Standard"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: -10, Lincoln: 0, Hartford: 0, "Peer Review": 5, Telco: 3, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 6,
      caseLengthPreference: "Any",
      currentWorkload: 4,
      availability: "Available",
      onTimePercentage: 80,
      accuracyScore: 78.67,
      overallQualityScore: 80.95,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 16,
      revisionAvailability: "Available",
      lastSnapshot: "2024-02-16T12:34:56Z"
    },
    {
      id: 5,
      mra_id: 5,
      name: "Chris Ekundare",
      email: "chrisekundare@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_5.jpg",
      location: {
        country: "Nigeria",
        latitude: 6.9244,
        longitude: 3.9792,
        timezone: "Africa/Lagos"
      },
      clients: ["PFR", "Lincoln", "Hartford"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 5, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 7,
      caseLengthPreference: "≤200",
      currentWorkload: 5,
      availability: "Available",
      onTimePercentage: 98,
      accuracyScore: 89.57,
      overallQualityScore: 93.09,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 17,
      revisionAvailability: "Available",
      lastSnapshot: "2025-02-22T12:34:56Z"
    },
    {
      id: 6,
      mra_id: 6,
      name: "Dilay Ackan",
      email: "dilay.akcan@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_6.jpg",
      location: {
        country: "Turkey",
        latitude: 41.2082,
        longitude: 28.8784,
        timezone: "Europe/Istanbul"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "Telco", "NYL", "Standard", "LTC"],
      caseType: "Non-Psych",
      preferredSpecialties: ["PMR", "Physical Medicine & Rehabilitation"],
      nonPreferredSpecialties: [ "Addiction Medicine",
        "Allergy & Immunology",
        "Anesthesiology",
        "Brain Injury Medicine",
        "Cardiovascular Disease",
        "Cardiovascular Medicine",
        "Cardiology",
        "Child & Adolescent Psychiatry",
        "Chiropractic",
        "Clinical Informatics",
        "Colon & Rectal Surgery",
        "Critical Care",
        "Critical Care Medicine",
        "Dermatology",
        "Diabetes and Metabolism",
        "Endocrinology",
        "Emergency Medicine",
        "Family Medicine",
        "Forensic Pathology",
        "Foot Surgery",
        "Gastroenterology",
        "GI",
        "Geriatric Medicine",
        "General Preventive Medicine",
        "Hand Surgery",
        "Hematology",
        "Hospice & Palliative Medicine",
        "Infectious Disease",
        "Internal Medicine",
        "Medical Oncology",
        "Medical Toxicology",
        "Nephrology",
        "Neurology",
        "Neuromuscular Medicine",
        "Neuro-Ophthalmology",
        "Neuroophthalmology",
        "Neuropsychology",
        "Neurological Surgery",
        "Oncology",
        "Occupational Medicine",
        "Ophthalmology",
        "Orthopedic Surgery",
        "Otolaryngology",
        "Obstetrics & Gynecology",
        "Pain Management",
        "Pain Medicine",
        "Pathology",
        "Periodontics",
        "Pediatrics",
        "Plastic Surgery",
        "Podiatry",
        "Preventive Medicine",
        "Psychiatry",
        "Psychology",
        "Public Health",
        "Rheumatology",
        "Sleep Medicine",
        "Spine Surgery",
        "Surgery of the Hand",
        "Speech Pathology",
        "Toxicology",
        "Urology",
        "Vascular Surgery"],
      clientModifiers: { PFR: -40, Lincoln: 0, Hartford: 0, "Peer Review": 20, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 8,
      caseLengthPreference: "200-500",
      currentWorkload: 6,
      availability: "Available",
      onTimePercentage: 90,
      accuracyScore: 62.62,
      overallQualityScore: 74.92,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 18,
      revisionAvailability: "Available",
      lastSnapshot: "2025-02-09T12:34:56Z",
    },
    {
      id: 7,
      mra_id: 7,
      name: "Ebenezer Arisa",
      email: "ebenezerarisa17@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_7.jpg",
      location: {
        country: "Philippines",
        latitude: 13.5995,
        longitude: 122.9842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR", "Lincoln", "Hartford"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 2,
      caseLengthPreference: "500-1000",
      currentWorkload: 7,
      availability: "Full",
      onTimePercentage: 92,
      accuracyScore: 66.32,
      overallQualityScore: 76.94,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 19,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 8,
      mra_id: 8,
      name: "Emmanuel Uduigwome",
      email: "eo.uduigwome@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_8.jpg",
      location: {
        country: "Nigeria",
        latitude: 9.5244,
        longitude: 4.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["PFR", "Lincoln", "Hartford", "NYL"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 3,
      caseLengthPreference: "1000+",
      currentWorkload: 8,
      availability: "Full",
      onTimePercentage: 94,
      accuracyScore: 81.65,
      overallQualityScore: 87.24,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 20,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 9,
      mra_id: 9,
      name: "Eliza Gomez",
      email: "elizagomeztoro4545@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_9.jpg",
      location: {
        country: "Colombia",
        latitude: 5.7110,
        longitude: -76.0721,
        timezone: "America/Bogota"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "Telco", "NYL"],
      caseType: "Both",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 4,
      caseLengthPreference: "Any",
      currentWorkload: 0,
      availability: "Available",
      onTimePercentage: 85,
      accuracyScore: 67.74,
      overallQualityScore: 74.75,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 21,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 10,
      mra_id: 10,
      name: "Erika Sucgang",
      email: "theerikajee@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_10.jpg",
      location: {
        country: "Philippines",
        latitude: 17.5995,
        longitude: 120.9842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR", "Lincoln", "Hartford"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 5,
      caseLengthPreference: "≤200",
      currentWorkload: 1,
      availability: "Available",
      onTimePercentage: 94,
      accuracyScore: 61.9,
      overallQualityScore: 74.14,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 22,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 11,
      mra_id: 11,
      name: "Geni Payales",
      email: "grpayales@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_11.jpg",
      location: {
        country: "Philippines",
        latitude: 16.5995,
        longitude: 121.9842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 6,
      caseLengthPreference: "200-500",
      currentWorkload: 2,
      availability: "Available",
      onTimePercentage: 93,
      accuracyScore: 90.12,
      overallQualityScore: 90.72,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 23,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 12,
      mra_id: 12,
      name: "Ieva Puidoke",
      email: "Ieva.puidoke@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_12.jpg",
      location: {
        country: "Lithuania",
        latitude: 54.6872,
        longitude: 25.2797,
        timezone: "Europe/Vilnius"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "Telco"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 7,
      caseLengthPreference: "500-1000",
      currentWorkload: 3,
      availability: "Available",
      onTimePercentage: 92,
      accuracyScore: 62.5,
      overallQualityScore: 73.1,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 24,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 13,
      mra_id: 13,
      name: "Ileri Lawal",
      email: "ilerioluwalawal@outlook.com",
      headshotUrl: "https://example.com/headshots/mra_13.jpg",
      location: {
        country: "Nigeria",
        latitude: 8.5244,
        longitude: 5.6792,
        timezone: "Africa/Lagos"
      },
      clients: ["PFR"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 8,
      caseLengthPreference: "1000+",
      currentWorkload: 4,
      availability: "Available",
      onTimePercentage: 98,
      accuracyScore: 64.91,
      overallQualityScore: 75.4,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 25,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 14,
      mra_id: 14,
      name: "Iyanuoluwa Oni",
      email: "iyanuopemipo@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_14.jpg",
      location: {
        country: "Nigeria",
        latitude: 7.5244,
        longitude: 6.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "LTC"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 2,
      caseLengthPreference: "Any",
      currentWorkload: 5,
      availability: "Full",
      onTimePercentage: 92,
      accuracyScore: 66.67,
      overallQualityScore: 74.8,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 26,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 15,
      mra_id: 15,
      name: "Joshua Arisa",
      email: "joshuaarisa14@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_15.jpg",
      location: {
        country: "Philippines",
        latitude: 12.5995,
        longitude: 120.9842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR", "Lincoln", "LTC"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 3,
      caseLengthPreference: "≤200",
      currentWorkload: 6,
      availability: "Full",
      onTimePercentage: 95,
      accuracyScore: 58.97,
      overallQualityScore: 72.28,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 27,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 16,
      mra_id: 16,
      name: "Joan Ajayi",
      email: "joanoajayi@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_16.jpg",
      location: {
        country: "Philippines",
        latitude: 11.8995,
        longitude: 123.9842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Muckleshoot"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 4,
      caseLengthPreference: "200-500",
      currentWorkload: 7,
      availability: "Full",
      onTimePercentage: 86,
      accuracyScore: 55.56,
      overallQualityScore: 67.68,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 28,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 17,
      mra_id: 17,
      name: "Khwaish Vasnani",
      email: "khwaishvasnani@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_17.jpg",
      location: {
        country: "Philippines",
        latitude: 9.5995,
        longitude: 122.9842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "Telco", "NYL", "Muckleshoot", "Standard", "LTC"],
      caseType: "Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 5,
      caseLengthPreference: "500-1000",
      currentWorkload: 8,
      availability: "Full",
      onTimePercentage: 96,
      accuracyScore: 81.48,
      overallQualityScore: 87.49,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 29,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 18,
      mra_id: 18,
      name: "Lina Gutierrez",
      email: "linis2791@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_18.jpg",
      location: {
        country: "Colombia",
        latitude: 4.7110,
        longitude: -74.0721,
        timezone: "America/Bogota"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "Telco", "NYL", "Standard"],
      caseType: "Both",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 6,
      caseLengthPreference: "1000+",
      currentWorkload: 0,
      availability: "Available",
      onTimePercentage: 90,
      accuracyScore: 20.0,
      overallQualityScore: 47.75,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 30,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 19,
      mra_id: 19,
      name: "Mary Goyenechea",
      email: "lorensgee1@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_19.jpg",
      location: {
        country: "Philippines",
        latitude: 13.7295,
        longitude: 120.1842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "Telco", "NYL", "Standard"],
      caseType: "Both",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 7,
      caseLengthPreference: "Any",
      currentWorkload: 1,
      availability: "Available",
      onTimePercentage: 98,
      accuracyScore: 53.85,
      overallQualityScore: 68.51,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 31,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 20,
      mra_id: 20,
      name: "Mary Galos",
      email: "cornillezjoyce@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_20.jpg",
      location: {
        country: "Philippines",
        latitude: 18.0995,
        longitude: 121.9842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR", "NYL"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 8,
      caseLengthPreference: "≤200",
      currentWorkload: 2,
      availability: "Available",
      onTimePercentage: 88,
      accuracyScore: 78.72,
      overallQualityScore: 83.53,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 32,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 21,
      mra_id: 21,
      name: "Maja Loja",
      email: "lojamaja@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_21.jpg",
      location: {
        country: "Philippines",
        latitude: 14.6995,
        longitude: 121.9842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "Telco", "NYL", "Standard"],
      caseType: "Both",
      preferredSpecialties: ["Medical Toxicology"],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 8,
      caseLengthPreference: "200-500",
      currentWorkload: 3,
      availability: "Available",
      onTimePercentage: 95,
      accuracyScore: 67.68,
      overallQualityScore: 78.56,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 22,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 22,
      mra_id: 22,
      name: "Next Reviewer",
      email: "test@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_22.jpg",
      location: {
        country: defaultTz.country,
        latitude: defaultTz.baseLat,
        longitude: defaultTz.baseLng,
        timezone: defaultTz.timezone
      },
      clients: ["PFR", "Lincoln", "Hartford"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 3,
      caseLengthPreference: "500-1000",
      currentWorkload: 4,
      availability: "Full",
      onTimePercentage: 82,
      accuracyScore: 87.5,
      overallQualityScore: 86.1,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 34,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 23,
      mra_id: 23,
      name: "Oluseye Oluremi",
      email: "oluseyekoluremi@su.edu.ph",
      headshotUrl: "https://example.com/headshots/mra_23.jpg",
      location: {
        country: "Nigeria",
        latitude: 7.5244,
        longitude: 3.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Standard"],
      caseType: "Non-Psych",
      dailyCaseLimit: 4,
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      caseLengthPreference: "1000+",
      currentWorkload: 5,
      availability: "Full",
      onTimePercentage: 95,
      accuracyScore: 96.15,
      overallQualityScore: 95.89,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 35,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 24,
      mra_id: 24,
      name: "Oluwadamilola Ogunsemowo",
      email: "damilolamogunsemowo@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_24.jpg",
      location: {
        country: "Nigeria",
        latitude: 6.8244,
        longitude: 5.9792,
        timezone: "Africa/Lagos"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Standard"],
      caseType: "Non-Psych",
      dailyCaseLimit: 5,
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      caseLengthPreference: "Any",
      currentWorkload: 6,
      availability: "Full",
      onTimePercentage: 83,
      accuracyScore: 80.0,
      overallQualityScore: 81.6,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 36,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 25,
      mra_id: 25,
      name: "Thomas Oyinlola",
      email: "thomasoyinlola@yahoo.com",
      headshotUrl: "https://example.com/headshots/mra_25.jpg",
      location: {
        country: "Nigeria",
        latitude: 5.5244,
        longitude: 5.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "Standard"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 6,
      caseLengthPreference: "≤200",
      currentWorkload: 7,
      availability: "Full",
      onTimePercentage: 95,
      accuracyScore: 82.61,
      overallQualityScore: 86.32,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 12, // 12 (explicit)
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 26,
      mra_id: 26,
      name: "Ravit Haleva",
      email: "ravithaleva@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_26.jpg",
      location: {
        country: "Turkey",
        latitude: 41.0082,
        longitude: 28.9784,
        timezone: "Europe/Istanbul"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "Telco", "NYL", "Standard", "LTC", "Muckleshoot"],
      caseType: "Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 7,
      caseLengthPreference: "200-500",
      currentWorkload: 8,
      availability: "Full",
      onTimePercentage: 95,
      accuracyScore: 83.33,
      overallQualityScore: 87.8,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 13,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 27,
      mra_id: 27,
      name: "Sarah Watkins",
      email: "sarahw445@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_27.jpg",
      location: {
        country: "Philippines",
        latitude: 8.5995,
        longitude: 125.9842,
        timezone: "Asia/Manila"
      },
      clients: ["Standard"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 8,
      caseLengthPreference: "500-1000",
      currentWorkload: 0,
      availability: "Available",
      onTimePercentage: 76,
      accuracyScore: 49.21,
      overallQualityScore: 61.87,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 14,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 28,
      mra_id: 28,
      name: "Shaila Maramara",
      email: "shailamaramara@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_28.jpg",
      location: {
        country: "Philippines",
        latitude:9.5995,
        longitude: 123.9842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Standard"],
      caseType: "Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 2,
      caseLengthPreference: "1000+",
      currentWorkload: 1,
      availability: "Available",
      onTimePercentage: 94,
      accuracyScore: 64.29,
      overallQualityScore: 74.17,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 15,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 29,
      mra_id: 29,
      name: "Vincent Medicielo",
      email: "medicielo.prosvincent@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_29.jpg",
      location: {
        country: "Philippines",
        latitude: 15.2995,
        longitude: 121.1842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR", "NYL"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 3,
      caseLengthPreference: "Any",
      currentWorkload: 2,
      availability: "Available",
      onTimePercentage: 99,
      accuracyScore: 83.16,
      overallQualityScore: 88.44,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 16,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 30,
      mra_id: 30,
      name: "Will Smith",
      email: "will@peerlinkmedical.com",
      headshotUrl: "https://example.com/headshots/mra_30.jpg",
      location: {
        country: "United States",
        latitude: 33.4171,
        longitude: -86.6111,
        timezone: "America/Chicago"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "Telco", "NYL", "Standard"],
      caseType: "Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 4,
      caseLengthPreference: "≤200",
      currentWorkload: 3,
      availability: "Available",
      onTimePercentage: 85,
      accuracyScore: 50.0,
      overallQualityScore: 64.2,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 17,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 31,
      mra_id: 31,
      name: "Yllana Saavedra",
      email: "iyannsaavedra@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_31.jpg",
      location: {
        country: "Philippines",
        latitude: 12.2185,
        longitude: 121.0842,
        timezone: "Asia/Manila"
      },
      clients: ["PFR"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 5,
      caseLengthPreference: "200-500",
      currentWorkload: 4,
      availability: "Available",
      onTimePercentage: 92,
      accuracyScore: 93.65,
      overallQualityScore: 91.74,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 18,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 32,
      mra_id: 32,
      name: "Temilola Edun",
      email: "temilolaedun@outlook.com",
      headshotUrl: "https://example.com/headshots/mra_32.jpg",
      location: {
        country: "Nigeria",
        latitude: 5.5244,
        longitude: 7.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["PFR"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 6,
      caseLengthPreference: "500-1000",
      currentWorkload: 5,
      availability: "Available",
      onTimePercentage: 96,
      accuracyScore: 94.59,
      overallQualityScore: 93.66,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 19,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 33,
      mra_id: 33,
      name: "Toluwani Merari",
      email: "nt.merari@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_33.jpg",
      location: {
        country: "Nigeria",
        latitude: 6.5244,
        longitude: 8.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["PFR", "Lincoln"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 7,
      caseLengthPreference: "1000+",
      currentWorkload: 6,
      availability: "Available",
      onTimePercentage: 97,
      accuracyScore: 88.57,
      overallQualityScore: 90.24,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 20,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 34,
      mra_id: 34,
      name: "Oluwapelumi Gabriel",
      email: "pelumio.gabriel@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_34.jpg",
      location: {
        country: "Nigeria",
        latitude: 8.5244,
        longitude: 9.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["PFR", "Lincoln"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 8,
      caseLengthPreference: "Any",
      currentWorkload: 7,
      availability: "Available",
      onTimePercentage: 97,
      accuracyScore: 94.2,
      overallQualityScore: 93.17,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 21,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 35,
      mra_id: 35,
      name: "Tolulope Ajayi",
      email: "to.ajayimd@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_35.jpg",
      location: {
        country: "Nigeria",
        latitude: 9.5244,
        longitude: 6.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["PFR", "Lincoln"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 2,
      caseLengthPreference: "≤200",
      currentWorkload: 8,
      availability: "Full",
      onTimePercentage: 98,
      accuracyScore: 87.5,
      overallQualityScore: 90.24,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 22,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 36,
      mra_id: 36,
      name: "Addison Marimberga",
      email: "addison@peerlinkmedical.com",
      headshotUrl: "https://example.com/headshots/mra_36.jpg",
      location: {
        country: "United States",
        latitude: 33.4621,
        longitude: -86.5210,
        timezone: "America/Chicago"
      },
      clients: ["PFR", "Lincoln", "Hartford", "Peer Review", "Telco", "NYL", "Standard"],
      caseType: "Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 3,
      caseLengthPreference: "200-500",
      currentWorkload: 0,
      availability: "Available",
      onTimePercentage: 95,
      accuracyScore: 84.31,
      overallQualityScore: 88.69,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 23,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 37,
      mra_id: 37,
      name: "Goodluck Odii",
      email: "goodluckmodii@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_37.jpg",
      location: {
        country: "Nigeria",
        latitude: 9.8244,
        longitude: 5.8792,
        timezone: "Africa/Lagos"
      },
      clients: ["Lincoln"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 4,
      caseLengthPreference: "500-1000",
      currentWorkload: 1,
      availability: "Available",
      onTimePercentage: 96,
      accuracyScore: 89.74,
      overallQualityScore: 90.95,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 24,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 38,
      mra_id: 38,
      name: "Fiyinfoluwa Yemi-Lebi",
      email: "fiyinmlebi@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_38.jpg",
      location: {
        country: "Nigeria",
        latitude: 7.1244,
        longitude: 9.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["Lincoln", "Hartford"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 5,
      caseLengthPreference: "1000+",
      currentWorkload: 2,
      availability: "Available",
      onTimePercentage: 98,
      accuracyScore: 94.81,
      overallQualityScore: 94.33,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 25,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 39,
      mra_id: 39,
      name: "Elizabeth Adeyanju",
      email: "elizabethmadeyanju@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_39.jpg",
      location: {
        country: "Nigeria",
        latitude: 10.5244,
        longitude: 5.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["Lincoln", "Standard"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 6,
      caseLengthPreference: "Any",
      currentWorkload: 3,
      availability: "Available",
      onTimePercentage: 96,
      accuracyScore: 91.84,
      overallQualityScore: 90.75,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 26,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 40,
      mra_id: 40,
      name: "Opemipo Ade-Akingboye",
      email: "opemipomade@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_40.jpg",
      location: {
        country: "Nigeria",
        latitude: 6.1123,
        longitude: 4.8192,
        timezone: "Africa/Lagos"
      },
      clients: ["Lincoln"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 7,
      caseLengthPreference: "≤200",
      currentWorkload: 4,
      availability: "Available",
      onTimePercentage: 97,
      accuracyScore: 94.03,
      overallQualityScore: 93.17,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 27,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 41,
      mra_id: 41,
      name: "Lebari Damgbor",
      email: "lebarimdamgbor@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_41.jpg",
      location: {
        country: "Nigeria",
        latitude: 12.5244,
        longitude: 7.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["Lincoln", "Hartford"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 8,
      caseLengthPreference: "200-500",
      currentWorkload: 5,
      availability: "Available",
      onTimePercentage: 96,
      accuracyScore: 92.73,
      overallQualityScore: 91.59,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 28,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 42,
      mra_id: 42,
      name: "Uchechukwu Ejike",
      email: "uchemejike@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_42.jpg",
      location: {
        country: "Nigeria",
        latitude: 11.1244,
        longitude: 6.3712,
        timezone: "Africa/Lagos"
      },
      clients: ["Lincoln", "Hartford"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 2,
      caseLengthPreference: "500-1000",
      currentWorkload: 6,
      availability: "Full",
      onTimePercentage: 98,
      accuracyScore: 95.7,
      overallQualityScore: 95.67,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 29,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 43,
      mra_id: 43,
      name: "Oluwaseyi Adare",
      email: "oluwaseyimadare@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_43.jpg",
      location: {
        country: "Nigeria",
        latitude: 8.5944,
        longitude: 6.0312,
        timezone: "Africa/Lagos"
      },
      clients: ["Lincoln", "Hartford"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 3,
      caseLengthPreference: "1000+",
      currentWorkload: 7,
      availability: "Full",
      onTimePercentage: 97,
      accuracyScore: 86.75,
      overallQualityScore: 93.17,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 30,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 44,
      mra_id: 44,
      name: "Mariam Akubo",
      email: "mariammakubo@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_44.jpg",
      location: {
        country: "Nigeria",
        latitude: 6.5244,
        longitude: 9.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["Lincoln", "Hartford"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 4,
      caseLengthPreference: "Any",
      currentWorkload: 8,
      availability: "Full",
      onTimePercentage: 96,
      accuracyScore: 96.55,
      overallQualityScore: 96.93,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 31,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 45,
      mra_id: 45,
      name: "Jamiu Olurunnisola",
      email: "jamiumolorunnisola@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_45.jpg",
      location: {
        country: "Nigeria",
        latitude: 9.5244,
        longitude: 12.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["Lincoln"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 5,
      caseLengthPreference: "≤200",
      currentWorkload: 0,
      availability: "Available",
      onTimePercentage: 92,
      accuracyScore: 95.12,
      overallQualityScore: 93.57,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 32,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 46,
      mra_id: 46,
      name: "Al Ameen Kalejaiye",
      email: "alameenmkalejaiye@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_46.jpg",
      location: {
        country: "Nigeria",
        latitude: 10.5244,
        longitude: 11.1792,
        timezone: "Africa/Lagos"
      },
      clients: ["Lincoln"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 6,
      caseLengthPreference: "200-500",
      currentWorkload: 1,
      availability: "Available",
      onTimePercentage: 94,
      accuracyScore: 91.87,
      overallQualityScore: 92.27,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 33,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 47,
      mra_id: 47,
      name: "Solomon Bailey",
      email: "solomonmbailey@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_47.jpg",
      location: {
        country: "Nigeria",
        latitude: 11.5244,
        longitude: 11.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["Lincoln", "NYL"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 7,
      caseLengthPreference: "500-1000",
      currentWorkload: 2,
      availability: "Available",
      onTimePercentage: 95,
      accuracyScore: 82.61,
      overallQualityScore: 86.32,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 34,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    },
    {
      id: 48,
      mra_id: 48,
      name: "Oluwafemi Durojaiye",
      email: "oluwafemimdurojaiye@gmail.com",
      headshotUrl: "https://example.com/headshots/mra_48.jpg",
      location: {
        country: "Nigeria",
        latitude: 11.5244,
        longitude: 9.3792,
        timezone: "Africa/Lagos"
      },
      clients: ["Lincoln"],
      caseType: "Non-Psych",
      preferredSpecialties: [],
      nonPreferredSpecialties: [],
      clientModifiers: { PFR: 0, Lincoln: 0, Hartford: 0, "Peer Review": 0, Telco: 0, NYL: 0, Standard: 0, LTC: 0 },
      dailyCaseLimit: 8,
      caseLengthPreference: "1000+",
      currentWorkload: 3,
      availability: "Available",
      onTimePercentage: 95,
      accuracyScore: 96.15,
      overallQualityScore: 95.89,
      costPerCase: { PFR: 20, NYL: 15, LTC: 30, Telco: 30, Lincoln: 20, Hartford: 20, "Peer Review": 25, Muckleshoot: 15, Standard: 20 },
      turnaroundTime: 35,
      revisionAvailability: "Available",
      lastSnapshot: "2025-03-09T12:34:56Z"
    }
  ];
  
  export { caseLengthOptions, getTzInfo };
  export default AdminFLData;
  